export const defectImages = {
    "Accessories defects": "../assets/Img/accessories-defects.jpg",
    "Broken Stitching": "/assets/Img/broken-stitching.jpg",
    "Chalk marks/pencil marks": "/assets/Img/chalk-marks-pencil-marks.jpg",
    "Color-Shading / shaded parts": "/assets/Img/color-shading-shaded-parts.jpg",
    "Cracked seam": "/assets/Img/cracked-seam.jpg",
    "Cut damage": "/assets/Img/cut-damage.jpg",
    "Defective Stitching": "/assets/Img/defective-stitching.jpg",
    "Dirty Mark - Others": "/assets/Img/dirty-mark-others.jpg",
    "Drop Stitch": "/assets/Img/drop-stitch.jpg",
    "Embroidery/Applique-Others (Heat transfer / printing defects)": "/assets/Img/embroidery-applique-others-heat-transfer-printing-defects.jpg",
    "Fullness": "/assets/Img/fullness.jpg",
    "Insecure backstitch": "/assets/Img/insecure-backstitch.jpg",
    "Join Stitching - Misalign": "/assets/Img/join-stitching-misalign.jpg",
    "Knitted Defects - Others": "/assets/Img/knitted-defects-others.jpg",
    "Needle Holes": "/assets/Img/needle-holes.jpg",
    "Oil Spots": "/assets/Img/oil-spots.jpg",
    "Others": "/assets/Img/others.jpg",
    "Pleated Seam": "/assets/Img/pleated-seam.jpg",
    "Poor Neck Shape": "/assets/Img/poor-neck-shape.jpg",
    "Poor color matching against standard": "/assets/Img/poor-color-matching-against-standard.jpg",
    "Poor pressing / Ironing": "/assets/Img/poor-pressing-ironing.jpg",
    "Raw Edge": "/assets/Img/raw-edge.jpg",
    "SPI (Stitch density: Too Loose / Tight)": "/assets/Img/spi-stitch-density-too-loose-tight.jpg",
    "Seam Waviness": "/assets/Img/seam-waviness.jpg",
    "Seam puckering": "/assets/Img/seam-puckering.jpg",
    "Skipped stitches": "/assets/Img/skipped-stitches.jpg",
    "Sticker/label : Damaged/Incorrect": "/assets/Img/sticker-label-damaged-incorrect.jpg",
    "Stitching- Bar tacks: missing": "/assets/Img/stitching-bar-tacks-missing.jpg",
    "Stitching-Seam slippage": "/assets/Img/stitching-seam-slippage.jpg",
    "Stitching-Seam-Open": "/assets/Img/stitching-seam-open.jpg",
    "Trimming & Thread: Untrimmed": "/assets/Img/trimming-thread-untrimmed.jpg",
    "Twisted seam / Seam Rolling": "/assets/Img/twisted-seam-seam-rolling.jpg",
    "Uneven seam": "/assets/Img/uneven-seam.jpg",
    "Workmanship-Slanted/Uncentered": "/assets/Img/workmanship-slanted-uncentered.jpg",
    "Zipper Defects": "/assets/Img/zipper-defects.jpg",
  };

  export const defaultDefectImage = "/assets/Img/default-defect.jpg";