export const defectImages = {
  "Accessories defects": "/qcc.png",
  "Broken Stitching": "/qcc.png",
  "Chalk marks/pencil marks": "/chalk.png",
  "Color-Shading / shaded parts": "/color.png",
  "Cracked seam": "/qcc.png",
  "Cut damage": "/cut.png",
  "Defective Stitching": "/stitches.png",
  "Dirty Mark - Others": "/qcc.png",
  "Drop Stitch": "/qcc.png",
  "Embroidery/Applique-Others (Heat transfer / printing defects)": "/qcc.png",
  "Fullness": "/qcc.png",
  "Insecure backstitch": "/qcc.png",
  "Join Stitching - Misalign": "/qcc.png",
  "Knitted Defects - Others": "/qcc.png",
  "Needle Holes": "/qcc.png",
  "Oil Spots": "/qcc.png",
  "Others": "/qcc.png",
  "Pleated Seam": "/qcc.png",
  "Poor Neck Shape": "/qcc.png",
  "Poor color matching against standard": "/qcc.png",
  "Poor pressing / Ironing": "/qcc.png",
  "Raw Edge": "/qcc.png",
  "SPI (Stitch density: Too Loose / Tight)": "/qcc.png",
  "Seam Waviness": "/qcc.png",
  "Seam puckering": "/qcc.png",
  "Skipped stitches": "/qcc.png",
  "Sticker/label : Damaged/Incorrect": "/qcc.png",
  "Stitching- Bar tacks: missing": "/qcc.png",
  "Stitching-Seam slippage": "/qcc.png",
  "Stitching-Seam-Open": "/qcc.png",
  "Trimming & Thread: Untrimmed": "/qcc.png",
  "Twisted seam / Seam Rolling": "/qcc.png",
  "Uneven seam": "/qcc.png",
  "Workmanship-Slanted/Uncentered": "/qcc.png",
  "Zipper Defects": "/qcc.png",
};
export const defectsList = {
  english: [
    { id: "Accessories defects", name: "Acessories defects"},
    { id: "Broken Stitching", name: "Broken Stitching"},
    { id: "Chalk marks/pencil marks",name:   "Chalk marks/pencil marks"},
    { id: "Color-Shading / shaded parts", name:     "Color-Shading /  shaded parts"},
    { id: "Cracked seam", name:    "Cracked  seam"},
    { id: "Cut damage", name:    "Cut damage"},
    { id: "Defective Stitching", name:  "Defective Stitching"},
    { id: "Dirty Mark - Others",  name:   "Dirty Mark - Others"},
    { id: "Drop Stitch",name: "Drop Stich"},
    { id: "Embroidery/Applique-Others (Heat transfer / printing defects)", name: "Embroidery/Applique-Others (Heat transfer / printing defects)"},
    { id: "Fullness", name: "Fullness"},
    { id: "Insecure backstitch", name: "Insecure backstitch"},
    { id: "Join Stitching - Misalign", name: "Join Stiching - Misalign"},
    { id: "Knitted Defects - Others",name: "Knitted Defects - Others"},
    { id: "Needle Holes", name: "Needle Holes"},
    { id: "Oil Spots", name:  "Oil Spots"},
    { id: "Others", name: "Others"},
    { id: "Pleated Seam", name: "Pleated Seam"},
    { id: "Poor Neck Shape", name: "Poor Neck Shape"},
    { id: "Poor color matching against standard", name: "Poor color matching against standard"},
    { id: "Poor pressing / Ironing", name: "Poor pressing / Ironing"},
    { id: "Raw Edge", name: "Raw Edge"},
    { id: "SPI (Stitch density: Too Loose / Tight)", name:"SPI (Stitch density: Too Loose / Tight)"},
    { id: "Seam Waviness", name:  "Seam Waviness"},
    { id: "Seam puckering", name: "Seam puckering"},
    { id: "Skipped stitches", name:  "Skipped stitches"},
    { id: "Sticker/label : Damaged/Incorrect",name:  "Sticker/label : Damaged/Incorrect"},
    { id: "Stitching- Bar tacks: missing", name: "Stitching- Bar tacks: missing"},
    { id: "Stitching-Seam slippage", name:  "Stitching-Seam slippage"},
    { id: "Stitching-Seam-Open", name: "Stitching-Seam-Open"},
    { id: "Trimming & Thread: Untrimmed", name: "Trimming & Thread: Untrimmed"},
    { id: "Twisted seam / Seam Rolling", name:  "Twisted seam / Seam Rolling"},
    { id: "Uneven seam", name: "Uneven seam"},
    { id: "Workmanship-Slanted/Uncentered", name: "Workmanship-Slanted/Uncentered"},
    { id: "Zipper Defects", name: "Zipper Defects"},
     ],
  khmer: [ 
    { id: "Accessories defects", name:  "បញ្ហាផ្លាក"},
    { id: "Broken Stitching", name:  "ដាច់អំបោះ"},
    { id: "Chalk marks/pencil marks",name:   "ស្នាមដីស/ខ្មៅដៃ"},
    { id: "Color-Shading / shaded parts", name:     "ខុសពណ៏រលោះ"},
    { id: "Cracked seam", name:    "រលោះអំបោះ"},
    { id: "Cut damage", name:    "កាត់រហែក"},
    { id: "Defective Stitching", name:  "អត់បានដេរ"},
    { id: "Dirty Mark - Others",  name:   "ប្រឡាក់"},
    { id: "Drop Stitch",name: "ធ្លាក់ទឹក"},
    { id: "Embroidery/Applique-Others (Heat transfer / printing defects)", name:  "ព្រីននិងប៉ាក់"},
    { id: "Fullness", name:  "ដកសាច់"},
    { id: "Insecure backstitch", name:  "ដេរអត់ជាប់ថ្នេរ"},
    { id: "Join Stitching - Misalign", name:  "តូចធំ"},
    { id: "Knitted Defects - Others",name:  "ឆ្នូតក្រណាត់"},
    { id: "Needle Holes", name: "ធ្លុះរន្ធ"},
    { id: "Oil Spots", name: "ប្រឡាក់ប្រេង"},
    { id: "Others", name:  "អាវកែផ្សេងៗ"},
    { id: "Pleated Seam", name:  "ដេរគៀប"},
    { id: "Poor Neck Shape", name: "ខូចរាងក"},
    { id: "Poor color matching against standard", name:  "ខុសពណ៌ពីគំរូ"},
    { id: "Poor pressing / Ironing", name: "អ៊ុតអត់ស្អាត"},
    { id: "Raw Edge", name: "សល់ជាយ/ព្រុយ"},
    { id: "SPI (Stitch density: Too Loose / Tight)", name:"ថ្នេរតឹង/ធូរពេក"},
    { id: "Seam Waviness", name:  "រលក"},
    { id: "Seam puckering", name:  "ជ្រួញ"},
    { id: "Skipped stitches", name: "លោតអៅបោះ"},
    { id: "Sticker/label : Damaged/Incorrect",name:  "ដេរខុសសេរីនិងដេរខុសផ្លាក"},
    { id: "Stitching- Bar tacks: missing", name: "ភ្លេចបាតិះ"},
    { id: "Stitching-Seam slippage", name:  "ធ្លាក់ថ្នេរ"},
    { id: "Stitching-Seam-Open", name: "រហែកថ្នេរ"},
    { id: "Trimming & Thread: Untrimmed", name:  "ព្រុយ"},
    { id: "Twisted seam / Seam Rolling", name: "ដេររមួល"},
    { id: "Uneven seam", name: "ដេរអត់ស្មើ"},
    { id: "Workmanship-Slanted/Uncentered", name: "មិនចំកណ្តាល"},
    { id: "Zipper Defects", name:  "បញ្ហារូត"},
  ],
  chinese: [
      
    { id: "Accessories defects", name:  "物料问题"},
    { id: "Broken Stitching", name: "斷線"},
    { id: "Chalk marks/pencil marks",name: "粉/笔印"},
    { id: "Color-Shading / shaded parts", name:   "色差"},
    { id: "Cracked seam", name:   "爆縫"},
    { id: "Cut damage", name:   "剪烂"},
    { id: "Defective Stitching", name: "漏車縫/漏空"},
    { id: "Dirty Mark - Others",  name:   "髒污"},
    { id: "Drop Stitch",name: "落坑"},
    { id: "Embroidery/Applique-Others (Heat transfer / printing defects)", name: "燙畫/印花/繡花"},
    { id: "Fullness", name:  "鼓起"},
    { id: "Insecure backstitch", name:  "不牢固"},
    { id: "Join Stitching - Misalign", name: "平车压线有大小"},
    { id: "Knitted Defects - Others",name: "布疵"},
    { id: "Needle Holes", name: "破洞 (包括針洞)"},
    { id: "Oil Spots", name: "油漬"},
    { id: "Others", name:  "其它返工"},
    { id: "Pleated Seam", name:  "打折"},
    { id: "Poor Neck Shape", name:  "领型不良"},
    { id: "Poor color matching against standard", name:  "染色不正確 - 次品/廢品"},
    { id: "Poor pressing / Ironing", name: "熨燙不良"},
    { id: "Raw Edge", name:"毛邊"},
    { id: "SPI (Stitch density: Too Loose / Tight)", name: "針距: 線緊/線鬆"},
    { id: "Seam Waviness", name:  "波浪"},
    { id: "Seam puckering", name:  "起皺"},
    { id: "Skipped stitches", name: "跳線"},
    { id: "Sticker/label : Damaged/Incorrect",name: "錯碼/車錯嘜頭"},
    { id: "Stitching- Bar tacks: missing", name:  "漏打枣 / 钮门"},
    { id: "Stitching-Seam slippage", name:  "缝合线滑移缺陷"},
    { id: "Stitching-Seam-Open", name:  "爆縫"},
    { id: "Trimming & Thread: Untrimmed", name:  "線頭"},
    { id: "Twisted seam / Seam Rolling", name: "扭/變形"},
    { id: "Uneven seam", name: "不對稱 / 長短不齊"},
    { id: "Workmanship-Slanted/Uncentered", name: "斜/不正中"},
    { id: "Zipper Defects", name: "拉链问题"},
  ],
  all: [
       
    { id: "Accessories defects", name: "Acessories defects \\ បញ្ហាផ្លាក \\物料问题"},
    { id: "Broken Stitching", name:    "Broken Stitching \\ ដាច់អំបោះ  \\斷線"},
    { id: "Chalk marks/pencil marks",name:  "Chalk marks/pencil marks \\ ស្នាមដីស/ខ្មៅដៃ \\粉/笔印"},
    { id: "Color-Shading / shaded parts", name:   "Color-Shading /  shaded parts \\ ខុសពណ៏ \\色差"},
    { id: "Cracked seam",  name:  "Cracked  seam \\ រលោះអំបោះ \\爆縫"},
    { id: "Cut damage", name:   "Cut damage \\ កាត់រហែក \\剪烂"},
    { id: "Defective Stitching", name:"Defective Stitching \\  អត់បានដេរ \\ 漏車縫/漏空"},
    { id: "Dirty Mark - Others",  name:   "Dirty Mark - Others \\ ប្រឡាក់  \\ 髒污"},
    { id: "Drop Stitch",name:"Drop Stich \\ ធ្លាក់ទឹក \\落坑"},
    { id: "Embroidery/Applique-Others (Heat transfer / printing defects)", name: "Embroidery/Applique-Others (Heat transfer / printing defects) \\ ព្រីននិងប៉ាក់ \\燙畫/印花/繡花"},
    { id: "Fullness", name:  "Fullness \\ ដកសាច់ \\鼓起"},
    { id: "Insecure backstitch", name: "Insecure backstitch \\  ដេរអត់ជាប់ \\不牢固"},
    { id: "Join Stitching - Misalign", name: "Join Stiching - Misalign \\ ថ្នេរតូចធំ \\平车压线有大小"},
    { id: "Knitted Defects - Others",name: "Knitted Defects - Others \\ ឆ្នូតក្រណាត់ \\布疵"},
    { id: "Needle Holes", name: "Needle Holes \\  ធ្លុះរន្ធ \\ 破洞 (包括針洞)"},
    { id: "Oil Spots", name: "Oil Spots \\ ប្រឡាក់ប្រេង \\油漬"},
    { id: "Others", name: "Others \\ អាវកែផ្សេងៗ \\其它返工"},
    { id: "Pleated Seam", name:  "Pleated Seam \\ ដេរគៀប \\打折"},
    { id: "Poor Neck Shape", name: "Poor Neck Shape \\ ខូចរាងក \\领型不良"},
    { id: "Poor color matching against standard", name: "Poor color matching against standard \\ ខុសពណ៌ពីគំរូ \\ 染色不正確 - 次品/廢品"},
    { id: "Poor pressing / Ironing", name: "Poor pressing / Ironing \\ អ៊ុតអត់ស្អាត \\熨燙不良"},
    { id: "Raw Edge", name:"Raw Edge \\  សល់ជាយ/ព្រុយ \\ 毛邊"},
    { id: "SPI (Stitch density: Too Loose / Tight)", name:"SPI (Stitch density: Too Loose / Tight) \\ ថ្នេរតឹង/ធូរពេក \\ 針距: 線緊/線鬆"},
    { id: "Seam Waviness", name: "Seam Waviness \\ រលក \\波浪"},
    { id: "Seam puckering", name: "Seam puckering \\  ជ្រួញ \\起皺"},
    { id: "Skipped stitches", name: "Skipped stitches \\ លោតអៅបោះ  \\ 跳線"},
    { id: "Sticker/label : Damaged/Incorrect",name: "Sticker/label : Damaged/Incorrect \\ ដេរខុសសេរីនិងដេរខុសផ្លាក \\ 錯碼/車錯嘜頭"},
    { id: "Stitching- Bar tacks: missing", name:  "Stitching- Bar tacks: missing \\ ភ្លេចបាតិះ \\漏打枣 / 钮门"},
    { id: "Stitching-Seam slippage", name: "Stitching-Seam slippage \\ ធ្លាក់ថ្នេរ \\缝合线滑移缺陷"},
    { id: "Stitching-Seam-Open", name: "Stitching-Seam-Open \\ រហែកថ្នេរ \\爆縫"},
    { id: "Trimming & Thread: Untrimmed", name: "Trimming & Thread: Untrimmed \\ ព្រុយ \\ 線頭"},
    { id: "Twisted seam / Seam Rolling", name: "Twisted seam / Seam Rolling \\ ដេររមួល \\扭/變形"},
    { id: "Uneven seam", name: "Uneven seam \\ ដេរអត់ស្មើ \\不對稱 / 長短不齊"},
    { id: "Workmanship-Slanted/Uncentered", name:  "Workmanship-Slanted/Uncentered \\ មិនចំកណ្តាល \\斜/不正中"},
    { id: "Zipper Defects", name: "Zipper Defects \\ បញ្ហារូត \\拉链问题"},
  ],
};

// Common indices for all languages
export const commonDefectIndices = [0, 1, 2, 5];
export const typeOneDefectIndices = [10, 11, 12];

// Simplified common defects object
export const commonDefects = {
  english: commonDefectIndices,
  khmer: commonDefectIndices,
  chinese: commonDefectIndices,
  all: commonDefectIndices,
};

// Simplified type one defects object
export const TypeOneDefects = {
  english: typeOneDefectIndices,
  khmer: typeOneDefectIndices,
  chinese: typeOneDefectIndices,
  all: typeOneDefectIndices,
};

