export const defectImages = {
    "Accessories defects": "/qcc.png",
    "Broken Stitching": "/qcc.png",
    "Chalk marks/pencil marks": "/chalk.png",
    "Color-Shading / shaded parts": "/color.png",
    "Cracked seam": "/qcc.png",
    "Cut damage": "/cut.png",
    "Defective Stitching": "/stitches.png",
    "Dirty Mark - Others": "/qcc.png",
    "Drop Stitch": "/qcc.png",
    "Embroidery/Applique-Others (Heat transfer / printing defects)": "/qcc.png",
    "Fullness": "/qcc.png",
    "Insecure backstitch": "/qcc.png",
    "Join Stitching - Misalign": "/qcc.png",
    "Knitted Defects - Others": "/qcc.png",
    "Needle Holes": "/qcc.png",
    "Oil Spots": "/qcc.png",
    "Others": "/qcc.png",
    "Pleated Seam": "/qcc.png",
    "Poor Neck Shape": "/qcc.png",
    "Poor color matching against standard": "/qcc.png",
    "Poor pressing / Ironing": "/qcc.png",
    "Raw Edge": "/qcc.png",
    "SPI (Stitch density: Too Loose / Tight)": "/qcc.png",
    "Seam Waviness": "/qcc.png",
    "Seam puckering": "/qcc.png",
    "Skipped stitches": "/qcc.png",
    "Sticker/label : Damaged/Incorrect": "/qcc.png",
    "Stitching- Bar tacks: missing": "/qcc.png",
    "Stitching-Seam slippage": "/qcc.png",
    "Stitching-Seam-Open": "/qcc.png",
    "Trimming & Thread: Untrimmed": "/qcc.png",
    "Twisted seam / Seam Rolling": "/qcc.png",
    "Uneven seam": "/qcc.png",
    "Workmanship-Slanted/Uncentered": "/qcc.png",
    "Zipper Defects": "/qcc.png",
  };