export const defectsList = {
  english: [
    { name: "Accessories defects", imageUrl: "/qcc.png" },
    { name: "Broken Stitching", imageUrl: "/qcc.png" },
    { name: "Chalk marks/pencil marks", imageUrl: "/qcc.png" },
    { name: "Color-Shading / shaded parts", imageUrl: "/qcc.png" },
    { name: "Cracked seam", imageUrl: "/qcc.png" },
    { name: "Cut damage", imageUrl: "/qcc.png" },
    { name: "Defective Stitching", imageUrl: "/qcc.png" },
    { name: "Dirty Mark - Others", imageUrl: "/qcc.png" },
    { name: "Drop Stitch", imageUrl: "/qcc.png" },
    { name: "Embroidery/Applique-Others (Heat transfer / printing defects)", imageUrl: "/qcc.png" },
    { name: "Fullness", imageUrl: "/qcc.png" },
    { name: "Insecure backstitch", imageUrl: "/qcc.png" },
    { name: "Join Stitching - Misalign", imageUrl: "/qcc.png" },
    { name: "Knitted Defects - Others", imageUrl: "/qcc.png" },
    { name: "Needle Holes", imageUrl: "/qcc.png" },
    { name: "Oil Spots", imageUrl: "/qcc.png" },
    { name: "Others", imageUrl: "/qcc.png" },
    { name: "Pleated Seam", imageUrl: "/qcc.png" },
    { name: "Poor Neck Shape", imageUrl: "/qcc.png" },
    { name: "Poor color matching against standard", imageUrl: "/qcc.png" },
    { name: "Poor pressing / Ironing", imageUrl: "/qcc.png" },
    { name: "Raw Edge", imageUrl: "/qcc.png" },
    { name: "SPI (Stitch density: Too Loose / Tight)", imageUrl: "/qcc.png" },
    { name: "Seam Waviness", imageUrl: "/qcc.png" },
    { name: "Seam puckering", imageUrl: "/qcc.png" },
    { name: "Skipped stitches", imageUrl: "/qcc.png" },
    { name: "Sticker/label : Damaged/Incorrect", imageUrl: "/qcc.png" },
    { name: "Stitching- Bar tacks: missing", imageUrl: "/qcc.png" },
    { name: "Stitching-Seam slippage", imageUrl: "/qcc.png" },
    { name: "Stitching-Seam-Open", imageUrl: "/qcc.png" },
    { name: "Trimming & Thread: Untrimmed", imageUrl: "/qcc.png" },
    { name: "Twisted seam / Seam Rolling", imageUrl: "/qcc.png" },
    { name: "Uneven seam", imageUrl: "/qcc.png" },
    { name: "Workmanship-Slanted/Uncentered", imageUrl: "/qcc.png" },
    { name: "Zipper Defects", imageUrl: "/qcc.png" },
  ],
  khmer: [
    { name: "បញ្ហាផ្លាក", imageUrl: "/qcc.png" },
    { name: "ដាច់អំបោះ", imageUrl: "/qcc.png" },
    { name: "ស្នាមដីស/ខ្មៅដៃ", imageUrl: "/qcc.png" },
    { name: "ខុសពណ៏រលោះ", imageUrl: "/qcc.png" },
    { name: "រលោះអំបោះ", imageUrl: "/qcc.png" },
    { name: "កាត់រហែក", imageUrl: "/qcc.png" },
    { name: "អត់បានដេរ", imageUrl: "/qcc.png" },
    { name: "ប្រឡាក់", imageUrl: "/qcc.png" },
    { name: "ធ្លាក់ទឹក", imageUrl: "/qcc.png" },
    { name: "ព្រីននិងប៉ាក់", imageUrl: "/qcc.png" },
    { name: "ដកសាច់", imageUrl: "/qcc.png" },
    { name: "ដេរអត់ជាប់ថ្នេរ", imageUrl: "/qcc.png" },
    { name: "តូចធំ", imageUrl: "/qcc.png" },
    { name: "ឆ្នូតក្រណាត់", imageUrl: "/qcc.png" },
    { name: "ធ្លុះរន្ធ", imageUrl: "/qcc.png" },
    { name: "ប្រឡាក់ប្រេង", imageUrl: "/qcc.png" },
    { name: "អាវកែផ្សេងៗ", imageUrl: "/qcc.png" },
    { name: "ដេរគៀប", imageUrl: "/qcc.png" },
    { name: "ខូចរាងក", imageUrl: "/qcc.png" },
    { name: "ខុសពណ៌ពីគំរូ", imageUrl: "/qcc.png" },
    { name: "អ៊ុតអត់ស្អាត", imageUrl: "/qcc.png" },
    { name: "សល់ជាយ/ព្រុយ", imageUrl: "/qcc.png" },
    { name: "ថ្នេរតឹង/ធូរពេក", imageUrl: "/qcc.png" },
    { name: "រលក", imageUrl: "/qcc.png" },
    { name: "ជ្រួញ", imageUrl: "/qcc.png" },
    { name: "លោតអៅបោះ", imageUrl: "/qcc.png" },
    { name: "ដេរខុសសេរីនិងដេរខុសផ្លាក", imageUrl: "/qcc.png" },
    { name: "ភ្លេចបាតិះ", imageUrl: "/qcc.png" },
    { name: "ធ្លាក់ថ្នេរ", imageUrl: "/qcc.png" },
    { name: "រហែកថ្នេរ", imageUrl: "/qcc.png" },
    { name: "ព្រុយ", imageUrl: "/qcc.png" },
    { name: "ដេររមួល", imageUrl: "/qcc.png" },
    { name: "ដេរអត់ស្មើ", imageUrl: "/qcc.png" },
    { name: "មិនចំកណ្តាល", imageUrl: "/qcc.png" },
    { name: "បញ្ហារូត", imageUrl: "/qcc.png" },
  ],
  chinese: [
    { name: "物料问题", imageUrl: "/qcc.png" },
    { name: "斷線", imageUrl: "/qcc.png" },
    { name: "粉/笔印", imageUrl: "/qcc.png" },
    { name: "色差", imageUrl: "/qcc.png" },
    { name: "爆縫", imageUrl: "/qcc.png" },
    { name: "剪烂", imageUrl: "/qcc.png" },
    { name: "漏車縫/漏空", imageUrl: "/qcc.png" },
    { name: "髒污", imageUrl: "/qcc.png" },
    { name: "落坑", imageUrl: "/qcc.png" },
    { name: "燙畫/印花/繡花", imageUrl: "/qcc.png" },
    { name: "鼓起", imageUrl: "/qcc.png" },
    { name: "不牢固", imageUrl: "/qcc.png" },
    { name: "平车压线有大小", imageUrl: "/path/to/image13.jpg" },
    { name: "布疵", imageUrl: "/qcc.png" },
    { name: "破洞 (包括針洞)", imageUrl: "/qcc.png" },
    { name: "油漬", imageUrl: "/qcc.png" },
    { name: "其它返工", imageUrl: "/qcc.png" },
    { name: "打折", imageUrl: "/qcc.png" },
    { name: "领型不良", imageUrl: "/qcc.png" },
    { name: "染色不正確 - 次品/廢品", imageUrl: "/qcc.png" },
    { name: "熨燙不良", imageUrl: "/qcc.png" },
    { name: "毛邊", imageUrl: "/qcc.png" },
    { name: "針距: 線緊/線鬆", imageUrl: "/qcc.png" },
    { name: "波浪", imageUrl: "/qcc.png" },
    { name: "起皺", imageUrl: "/qcc.png" },
    { name: "跳線", imageUrl: "/qcc.png" },
    { name: "錯碼/車錯嘜頭", imageUrl: "/qcc.png" },
    { name: "漏打枣 / 钮门", imageUrl: "/qcc.png" },
    { name: "缝合线滑移缺陷", imageUrl: "/qcc.png" },
    { name: "爆縫", imageUrl: "/qcc.png" },
    { name: "線頭", imageUrl: "/qcc.png" },
    { name: "扭/變形", imageUrl: "/qcc.png" },
    { name: "不對稱 / 長短不齊", imageUrl: "/qcc.png" },
    { name: "斜/不正中", imageUrl: "/qcc.png" },
    { name: "拉链问题", imageUrl: "/qcc.png" },
  ],
  all: [
    { name: "Accessories defects \\ បញ្ហាផ្លាក \\物料问题", imageUrl: "/qcc.png" },
    { name: "Broken Stitching \\ ដាច់អំបោះ  \\斷線", imageUrl: "/qcc.png" },
    { name: "Chalk marks/pencil marks \\ ស្នាមដីស/ខ្មៅដៃ \\粉/笔印", imageUrl: "/qcc.png" },
    { name: "Color-Shading / shaded parts \\ ខុសពណ៏ \\色差", imageUrl: "/qcc.png" },
    { name: "Cracked seam \\ រលោះអំបោះ \\爆縫", imageUrl: "/qcc.png" },
    { name: "Cut damage \\ កាត់រហែក \\剪烂", imageUrl: "/qcc.png" },
    { name: "Defective Stitching \\ អត់បានដេរ \\ 漏車縫/漏空", imageUrl: "/qcc.png" },
    { name: "Dirty Mark - Others \\ ប្រឡាក់ \\ 髒污", imageUrl: "/qcc.png" },
    { name: "Drop Stitch \\ ធ្លាក់ទឹក \\落坑", imageUrl: "/qcc.png" },
    { name: "Embroidery/Applique-Others (Heat transfer / printing defects) \\ ព្រីននិងប៉ាក់ \\燙畫/印花/繡花", imageUrl: "/qcc.png" },
    { name: "Fullness \\ ដកសាច់ \\鼓起", imageUrl: "/qcc.png" },
    { name: "Insecure backstitch \\ ដេរអត់ជាប់ \\不牢固", imageUrl: "/qcc.png" },
    { name: "Join Stitching - Misalign \\ ថ្នេរតូចធំ \\平车压线有大小", imageUrl: "/qcc.png" },
    { name: "Knitted Defects - Others \\ ឆ្នូតក្រណាត់ \\布疵", imageUrl: "/qcc.png" },
    { name: "Needle Holes \\ ធ្លុះរន្ធ \\ 破洞 (包括針洞)", imageUrl: "/qcc.png" },
    { name: "Oil Spots \\ ប្រឡាក់ប្រេង \\油漬", imageUrl: "/qcc.png" },
    { name: "Others \\ អាវកែផ្សេងៗ \\其它返工", imageUrl: "/qcc.png" },
    { name: "Pleated Seam \\ ដេរគៀប \\打折", imageUrl: "/qcc.png" },
    { name: "Poor Neck Shape \\ ខូចរាងក \\领型不良", imageUrl: "/qcc.png" },
    { name: "Poor color matching against standard \\ ខុសពណ៌ពីគំរូ \\ 染色不正確 - 次品/廢品", imageUrl: "/qcc.png" },
    { name: "Poor pressing / Ironing \\ អ៊ុតអត់ស្អាត \\熨燙不良", imageUrl: "/qcc.png" },
    { name: "Raw Edge \\ សល់ជាយ/ព្រុយ \\ 毛邊", imageUrl: "/qcc.png" },
    { name: "SPI (Stitch density: Too Loose / Tight) \\ ថ្នេរតឹង/ធូរពេក \\ 針距: 線緊/線鬆", imageUrl: "/qcc.png" },
    { name: "Seam Waviness \\ រលក \\波浪", imageUrl: "/qcc.png" },
    { name: "Seam puckering \\ ជ្រួញ \\起皺", imageUrl: "/qcc.png" },
    { name: "Skipped stitches \\ លោតអៅបោះ \\ 跳線", imageUrl: "/qcc.png" },
    { name: "Sticker/label : Damaged/Incorrect \\ ដេរខុសសេរីនិងដេរខុសផ្លាក \\ 錯碼/車錯嘜頭", imageUrl: "/qcc.png" },
    { name: "Stitching- Bar tacks: missing \\ ភ្លេចបាតិះ \\漏打枣 / 钮门", imageUrl: "/qcc.png" },
    { name: "Stitching-Seam slippage \\ ធ្លាក់ថ្នេរ \\缝合线滑移缺陷", imageUrl: "/qcc.png" },
    { name: "Stitching-Seam-Open \\ រហែកថ្នេរ \\爆縫", imageUrl: "/qcc.png" },
    { name: "Trimming & Thread: Untrimmed \\ ព្រុយ \\ 線頭", imageUrl: "/qcc.png" },
    { name: "Twisted seam / Seam Rolling \\ ដេររមួល \\扭/變形", imageUrl: "/qcc.png" },
    { name: "Uneven seam \\ ដេរអត់ស្មើ \\不對稱 / 長短不齊", imageUrl: "/qcc.png" },
    { name: "Workmanship-Slanted/Uncentered \\ មិនចំកណ្តាល \\斜/不正中", imageUrl: "/qcc.png" },
    { name: "Zipper Defects \\ បញ្ហារូត \\拉链问题", imageUrl: "/qcc.png" },
  ],
};

export const factories = [
  "CJ2",
  "Combo H/Some",
  "Da Cheng",
  "De Quan",
  "Elite",
  "Elite-YM",
  "FHM",
  "HL",
  "JC",
  "Newest",
  "Sunicon",
  "VCOFF",
  "Wing Ying",
  "XYW",
  "ZX",
  "Enternal Fame",
  "KFINE",
  "SYD",
  "Hong Cheng",
  "Blue Vista",
];

export const styleCodes = [
  { code: "PTAR", customer: "Aritzia" },
  { code: "GPAR", customer: "Aritzia" },
  { code: "GPRT", customer: "Aritzia" },
  { code: "PTCOC", customer: "Costco" },
  { code: "PTCOT", customer: "Costco" },
  { code: "PTCOU", customer: "Costco" },
  { code: "PTCOR", customer: "Costco" },
  { code: "PTCOX", customer: "Costco" },
  { code: "PTCOM", customer: "Costco" },
  { code: "PTRT", customer: "Reitmans" },
  { code: "PTAF", customer: "A&F" },
];
